site_name: GA4GH Quality Control of Whole Genome Sequencing Specifications
site_url: https://ga4gh.github.io/wgs-qc
repo_url: https://github.com/ga4gh/quality-control-wgs
copyright: GA4GH Large Scale Genomics Workstream, wgs-qc team

nav:
  - Home: 
     - motivation.md
     - implemetations.md
  - metrics definitions: 
     - about.md 
    - alignments:
	- metrics_definitions/count-xxx.md
        - ...
    - variants:
       - ...mmd
    - terminologies.md

theme: readthedocs 
